FileApp/urls.py
"""
Here is where the urls for routing in our app happens
"""
from django.urls import path
from . import views

app_name = 'file_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.client_login, name='login'),
    path('logout/', views.sign_out, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('share_file/<int:file_id>/', views.share_file, name='share_file'),
    path('download_file/<int:file_id>/', views.download_file, name='download_file')
]

SecureFileSharingApplication/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("FileApp.urls", namespace='file_app'))
]

FileApp/models.py
from django.db import models
from django.contrib.auth.models import User  # For user authentication

class File(models.Model):
    """
    Class for storing file data
    """
    owner = models.ForeignKey(User, on_delete=models.CASCADE)  # The user who uploaded the file
    file_name = models.CharField(max_length=255)
    file = models.FileField(upload_to='uploads')
    file_key = models.CharField(max_length=500, default='None')
    encrypted = models.BooleanField(default=True)
    upload_date = models.DateTimeField(auto_now_add=True)
    shared_with = models.ManyToManyField(User, related_name='shared_files', blank=True)
    is_shared = models.BooleanField(default=False)
    file_size = models.PositiveIntegerField()  # File size in bytes
    file_type = models.CharField(max_length=100)  # Type of the file (e.g., text file)

    def get_file_size_kb(self):
        """
        Convert file size in bytes to KB
        """
        return round(self.file_size / (1024), 2)

    def __str__(self):
        """Returns the file name"""
        return self.file_name

class FileIntegrity(models.Model):
    """
    Class for storing file integrity data
    """
    file = models.ForeignKey(File, on_delete=models.CASCADE)
    sha256_hash = models.CharField(max_length=64)

    def __str__(self):
        """Returns the file name"""
        return self.file.file_name

class SharedFile(models.Model):
    """
    Class for shared file data
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    file = models.ForeignKey(File, on_delete=models.CASCADE)
    access_date = models.DateTimeField(auto_now=True) # optional
    permission = models.CharField(max_length=50)  # We can use this field to specify the level of access (e.g., read, edit, delete)
    file_name = models.CharField(max_length=255)

    def __str__(self):
        """Returns the username, filename and permission level"""
        return f"{self.user.username} - {self.file.file_name} ({self.permission})"
    class Meta:
        unique_together = ['user', 'file']  # Ensure each user can only share a file with a specific user once

FileApp/forms.py
"""
Classes for forms models
"""
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from FileApp.filevalidate import FileValidation

class UploadFileForm(forms.Form):
    """
    Form for uploading file
    """
    title = forms.CharField(max_length=255)
    file = forms.FileField(validators=[FileValidation(file_types=('text/plain',))])

class RegisterForm(UserCreationForm):
    """
    Form for user registration
    """
    class Meta:
        """Gets User class model"""
        model=User
        fields = ['username','email','password1','password2']

class LoginForm(forms.Form):
    """
    Form for user login
    """
    username = forms.CharField(max_length=65)
    password = forms.CharField(max_length=65, widget=forms.PasswordInput) 

class ShareFileForm(forms.Form):
    """
    Form for file sharing
    """
    def __init__(self, request, *args, **kwargs):
        super(ShareFileForm, self).__init__(*args, **kwargs)

        # Extract the user object from either User or request
        if isinstance(request, User):
            user = request
        elif hasattr(request, 'user'):
            user = request.user
        else:
            raise ValueError("Invalid user_or_request argument")

        # Exclude current user
        self.fields['shared_user'].queryset = User.objects.exclude(id = user.id)

    shared_user = forms.ModelChoiceField(
        queryset=User.objects.none(),
        empty_label="Select user to share with",
    )
    permission = forms.ChoiceField(
        choices=(
            ('read', 'Read'), # can download, not able to share file
            ('edit', 'Edit'), # can both download and share file
        ),
        initial='read',
        widget=forms.RadioSelect,
    )

FileApp/views.py
"""
Contains all the views for the app here
"""
import logging
import hashlib
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login as server_login,logout
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.exceptions import ValidationError
from FileApp.fileencrypt import *
from .forms import UploadFileForm, LoginForm, RegisterForm, ShareFileForm
from .models import File, SharedFile, FileIntegrity
from .userauth import *
from .filevalidate import has_permission
from .fernet import get_fernet_key

# Set up logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

def home(request):
    """
    Home page where navigation bar contains sign up / login links
    """
    return render(request, "home.html")

@csrf_protect
def register(request):
    """
    Register a new user account page
    """
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            # Sanitize input
            username = form.cleaned_data["username"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password1"]
            psw2 = form.cleaned_data["password2"]

            try:
                reg = UserRegistration(username, email, password, psw2)
                if User.objects.filter(username=username).exists():
                    messages.error(request, "Username is already in use")
                elif not reg.is_email_valid():
                    messages.error(request, "Email is invalid format")
                elif not reg.is_password_strong():
                    messages.error(request, "Password is not strong enough ")
                elif not reg.is_username_valid():
                    messages.error(request, "Username is not valid, must be alphanumeric and underscores ")
                elif not reg.are_passwords_matching():
                    messages.error("Passwords are not matching")
                else:
                    # passes all validations
                    hashed = reg.hash_password()
                    user = User(username=username, email=email, password=hashed.decode('utf-8'))
                    user.save()

                    messages.success(request,"Successful registration" )
                    server_login(request, user)
                    return redirect(reverse('file_app:home'))

                # all renders the form
                return render(request, "register.html", {"form": form})

            except Exception as e:
                messages.error(request, str(e))
        else:
            messages.error(request, "Form is invalid. Please check your input.")
    else:
        form = RegisterForm()
    return render(request, "register.html", {'form': form})

@csrf_protect
def client_login(request):
    """
    Login page for user
    """
    form = LoginForm()

    if request.method == "POST":
        form = LoginForm(request.POST)

        if form.is_valid():
            # Sanitize input
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            try:
                user = User.objects.get(username=username)
            except User.DoesNotExist:
                user = None

            if user is not None:
                if bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')):
                    server_login(request, user)
                    messages.success(request, f"Hi {user.username.title()}, welcome back!")
                    # Redirect to the user's file page
                    return redirect(reverse('file_app:profile'))
                else:
                    messages.error(request, "Invalid username or password")
            else:
                messages.error(request, "User does not exist")

    # Handle GET request or form errors
    return render(request, "login.html", {"form": form})

@csrf_protect
@login_required
def sign_out(request):
    """
    Sign out page where user is logged out. Redirects logout user to login page
    """
    logout(request)
    messages.success(request, 'You have been logged out.')
    return redirect(reverse('file_app:login'))

@login_required(login_url='file_app:login')
def profile(request):
    """
    Profile page where all files are listed. Login required to access page
    """
    # Get files shared with the current user
    shared_files = SharedFile.objects.filter(user=request.user).values('file')

    # Filter the File model to get shared files
    files = File.objects.filter(Q(owner=request.user) | Q(id__in=shared_files))

    # Zip the permission with the file  -- Anne
    files_with_permission = [{'file': file, 'has_permission': has_permission(file, request.user)} for file in files]

    context = {
        'files': files_with_permission,
    }

    return render(request, "profile.html", context)

@login_required(login_url='file_app:login')
@csrf_protect
def upload_file(request):
    """
    Upload file form and page. Login required to access page
    """
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)

        # Handle checking file integrity here and create file object to save after checking
        if form.is_valid():
            try:
                # checks if file title already exists for the user
                if File.objects.filter(owner=request.user, file_name=form.cleaned_data['title']).exists() or SharedFile.objects.filter(user=request.user, file__file_name = form.cleaned_data['title']).exists():
                    messages.error(request, "Title for file already exists in database. Please input a new title")
                    return render(request, "upload_file.html", {"form": form})

                key_string = get_fernet_key()
                encryptor = FileEncryptor(key_string)
                file = form.cleaned_data['file']

                # Read the content from the file     
                file.seek(0,0)
                file_content =file.read()

                # Calculate hash digest of file before saving
                hash_bfr_save = file_hashing(file_content)
                file.seek(0,0)
                encrypted_file = encryptor.file_encrypt(file)

                file_instance = File.objects.create(
                    owner=request.user,
                    file=encrypted_file,
                    file_name=form.cleaned_data['title'],
                    file_size=form.cleaned_data['file'].size,
                    file_key = key_string
                )

                # Saves the file object to database
                file_instance.save()

                # Calculate hash digest of file after saving
                decrypted_saved_file = encryptor.file_decrypt(file_instance.file)
                decrypted_saved_file.seek(0,0)
                decrypted_content = decrypted_saved_file.read()
                hash_after_save = file_hashing(decrypted_content)

                if hash_after_save == hash_bfr_save:
                    messages.success(request, 'File is successfully uploaded.')
                    intergrity = FileIntegrity(file=file_instance, sha256_hash=hash_after_save)
                    intergrity.save()
                    return redirect(reverse('file_app:profile')) # go back to profile page to see all the files
                else:
                    # Delete corrupted file
                    file_instance.delete()
                    messages.error(request, "File integrity compromised during upload, try again")

            except ValidationError as e:
                messages.error(request, e.message)
    else:
        form = UploadFileForm()
    return render(request, "upload_file.html", {"form": form})

@login_required(login_url='file_app:login')
@csrf_protect
def share_file(request, file_id):
    """
    Share file form and page. Login required to access page
    """
    try:
        # Get the file object using the file_id
        file_to_share = get_object_or_404(File, id=file_id)

        # Check if the file's owner is the current user
        if file_to_share.owner != request.user:
            messages.error(request, "You can only share your own files.")
            return redirect('file_app:profile')

        if request.method == 'POST':
            try:
                form = ShareFileForm(request, request.POST)
                if form.is_valid():
                    # sanatized user input
                    user_to_share = form.cleaned_data['shared_user']
                    permission = form.cleaned_data['permission']

                    # Check if a shared file entry with the same user and file already exists
                    shared_file, created = SharedFile.objects.get_or_create(
                        user=user_to_share,
                        file=file_to_share,
                        defaults={'permission': permission, 'file_name': file_to_share.file_name}
                    )

                    if not created:
                        # Update the existing entry with a new permission
                        shared_file.permission = permission
                        shared_file.save()
                        messages.success(request,f"File '{file_to_share.file_name}' has successfully been updated for {user_to_share.username}.")
                    else:
                        # Add comment to user - Anne
                        messages.success(request,f"File '{file_to_share.file_name}' has successfully been shared with {user_to_share.username}.")
            except Exception as e:
                messages.error(request, f"An error occurred while processing the form: {str(e)}")

FileApp/templates/base.html
<!-- Base html for getting shared elements for all pages -->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Secure File Sharing App</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <title>{%block title%}{%endblock title%}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-2">
            <a class="navbar-brand" href="{% if user.is_authenticated %}{% url 'file_app:profile' %}{% else %}{% url 'file_app:home' %}{% endif %}">File Sharing App</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                {%if user.is_authenticated%}
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'file_app:profile'%}">Files</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'file_app:upload_file'%}">Upload</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'file_app:logout'%}">Logout</a>
                    </li>
                {%else%}
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'file_app:login'%}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'file_app:register'%}">Register</a>
                    </li>
                {%endif%}
              </ul>
            </div>
        </nav>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <div class="container my-3">
            {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                        <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
		    {% endif %}

            {% block contents %}
            {% endblock contents %}
        </div>
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    </body>
</html>

FileApp/templates/home.html
{% extends './base.html' %}

FileApp/templates/login.html
<!DOCTYPE html>
{% extends './base.html' %}

{%block title%}
Login
{%endblock title%}

{%block contents%}
{%if error%}
<div class="alert alert-danger" role="alert">
    {{error}}
</div>
{%endif%}
<form action="{% url 'file_app:login' %}" method="post">
    {% csrf_token %}
    <div class="row lg-3">
        <div class="col-sm-6 {%if center%} mx-auto {%endif%}">
            {{form.as_p}}
        </div>    
    </div>            
    <input class="btn btn-primary" type="submit" value="Login">
</form>

<div class="my-2">
    <small class="text-muted">
        Need an account ? <a class="ml-2" href="{%url 'file_app:register'%}">Sign Up</a>
    </small>
</div>
{%endblock contents%}

FileApp/templates/logout.html
{% extends './base.html' %}

{% block contents %}

    <p>
        <a href="{% url 'file_app:login' %}">Log in again</a>
    </p>

{% endblock contents %}

FileApp/templates/profile.html
<!DOCTYPE html>
{% extends './base.html' %}

{% block title %}
Profile
{% endblock title %}

{% block contents %}

{% csrf_token %}
<div class="container">
    {% if request.user.is_authenticated %}
        <h1 class="text-center mt-4">{{ request.user.username | title }}'s Files</h1>
        <div class="row justify-content-center mt-4">
            <div class="col-md-8">
                <ul class="list-group">
                    {% if files is None %}
                        <li class="list-group-item text-center">First time here! Upload and share!</li>
                        <li class="list-group-item text-center">
                            <a href="{% url 'file_app:upload' %}" class="btn btn-primary">Upload</a>
                        </li>
                    {% else %}
                        {% for file_info in files %}
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                {% if file_info.file.owner == request.user %}
                                    <span class="text-success">My File</span>
                                {% else %}
                                    <span class="text-primary">Shared file</span>
                                {% endif %}
                                <span>{{ file_info.file.file_name }}</span>
                                <span class="badge bg-secondary rounded-pill">{{ file_info.file.get_file_size_kb }} KB</span>
                            {% if file_info.file.owner == request.user   %}
                                 <a href="{% url 'file_app:share_file' file_info.file.id %}" class="btn btn-primary">Share</a>
                            {% endif %}
                                {% if file_info.has_permission%}
                                    <a href="{% url 'file_app:download_file' file_info.file.id %}" class="btn btn-primary">Download</a>
                                {% endif %}

                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
        </div>
    {% else %}
        <h3 class="text-center mt-4">You are not logged in</h3>
    {% endif %}
</div>

{% endblock contents %}

FileApp/templates/register.html
<!DOCTYPE html>
{% extends './base.html' %} 

{%block title%}
Register
{%endblock title%}

{%block contents%}
{%if error%}
<div class="alert alert-danger" role="alert">
    {{error}}
</div>
{%endif%}
<form method="POST">
    {% csrf_token %}
    <div class="row lg-3">
        <div class="col-sm-6 {%if center%} mx-auto {%endif%}">
            <!-- {{ form.as_p }} -->
            {% for field in form %}
            <div class="form-group mb-3">
                {% if field.errors %}
                    {% for error in field.errors %}
                        <span class="invalid-feedback {%if error%}d-block{%endif%}">{{error}}</span>
                    {% endfor %}
                {%endif%}
                {{ field.label_tag }} {{ field }}
                {% if field.name == "password1" %}
                    <span class="helptext">
                        <ul>
                            <li>Your password can’t be too similar to your other personal information.</li>
                            <li>Your password must contain at least 8 characters.</li>
                            <li>Your password must contain at least one upper case, lower case, digit and special char "!@#$&/".</li>
                            <li>Your password can’t be entirely numeric.</li>
                      </ul>
                    </span>
    {%endif%}

            </div>
            {% endfor %}
        </div>    
    </div>
    <input class="btn btn-primary" type="submit" value="Register">
</form>

<div class="my-2">
    <small class="text-muted">
        Already have an account ? <a class="ml-2" href="{%url 'file_app:login'%}">Sign In</a>
    </small>
</div>
{%endblock contents%}

FileApp/templates/share_file.html
<!DOCTYPE html>
{% extends './base.html' %}

{% block title %}
Share File
{% endblock title %}

{% block contents %}
<div>
    <h3>Share File</h3>
    <form method="post" action="{% url 'file_app:share_file' file.id %}">
        {% csrf_token %}
        <input type="hidden" name="file_id" value="{{ file.id }}">
        <p class="mt-4">Select a user to share file with:</p>
        {{ form.shared_user }}
        <p class="mt-4">Select permission for user </p>
        <a href="#" class="btn btn-link">
            <i class="bi bi-info-circle"></i>
        </a>
        {{ form.permission }}
        <input class="mt-4" type="submit" value="Share with User">
    </form> 
</div>
    
{% endblock contents %}

FileApp/templates/upload_file.html
<!DOCTYPE html>
{% extends './base.html' %}

{%block title%}
Upload File
{%endblock title%}

{%block contents%}
{%if error%}
<div class="alert alert-danger" role="alert">
    {{error}}
</div>
{%endif%}
<div>
    <h3>Upload a file below</h3>
    <p>Accepted file types are text/plain</p>
    <form method ='post' enctype ="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value = "Submit">
    </form>
</div>            

{%endblock contents%}